<?php if($this->loggedIn){ ?>
<!DOCTYPE html> 
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Zend Framework &raquo; Agenda web :: Iván Olivares R.</title>
    <meta name="description" content="Agenda web desarrollada con ZendFramework y Bootstrap, from twitter.">
    <meta name="author" content="Iván Olivares R.">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="/img/favicon.ico">

    <!-- Stylesheets Bootstrap -->
    <link href="/bootstrap.css" rel="stylesheet" type="text/css">
    <link href="/css/override_defaults.css" rel="stylesheet" type="text/css" />
    
    <!-- Stylesheets personalizados -->
    <link href="/css/agenda.css" rel="stylesheet" type="text/css" />

    <!-- jQuery -->
    <script type="text/javascript" src="/js/jquery-1.6.4.min.js"></script>
    <!-- Bootstrap plugins -->
    <script type="text/javascript" src="/js/bootstrap-alerts.js"></script>
    <!-- TableSorter Plugin -->
    <script type="text/javascript" src="/js/jquery.tablesorter.min.js"></script>
    <!-- Scripts init -->
    <script type="text/javascript">
        $(function(){
           $("table#tablaDeContactos").tablesorter({ sortList: [[0,0]] });
        });
    </script>
  </head>

  <body>

    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="/">Zend Framework &raquo; Agenda</a>
          <ul class="nav">
            <li class="active"><a href="/">Inicio</a></li>
                <?php if($this->loggedIn){?>
                    <li><a href="/contactos/listar/">Contactos</a></li>
            
                <? }else { ?>
                    <li><a href="/user/">Login</a></li>
            
                 <? } ?>
          </ul>
          <?php if($this->loggedIn){?>
              <p class="pull-right">
                  Sesión iniciada como <a href="#!/">@<? echo $this->user->username; ?></a>
                  &nbsp;&nbsp;<a href="/user/logout/"><span class="label important">Salir</span></a>
              </p>
          <? } ?>
        </div>
      </div>
    </div>
    <div class="container">

      <div class="content">
        <div class="page-header">
          <h1>Zend Framework <small>Agenda de contactos</small> <span class="label success">βeta</span></h1>
        </div>
        <div class="row">
          <div class="span10">
            <?php echo $this->layout()->content; ?>
          </div>
        </div>
      </div>

      <footer>
        <p>&copy; Iván Olivares R. <? echo date("Y"); ?></p>
        <a href="http://framework.zend.com/" target="_blank">
            <img src="/img/PoweredBy_ZF_4LightBG.png" alt="" />
        </a>
        <a href="http://twitter.github.com/bootstrap/" target="_blank">
            <img src="/img/PoweredBy_bootstrap.png" alt="" />
        </a>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

<? }else {
    if(!$this->loggedIn) {
        echo $this->layout()->content;
    }else{
        header("Location: /user/");
    }
} ?>